app = "telegram-mass-sender"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = false
  min_machines_running = 1
  max_machines_running = 1

[[mounts]]
  source = "data"
  destination = "/app/data"

[[mounts]]
  source = "logs"
  destination = "/app/logs"
